### ISSUE TITLE
pxeveryshi needs perhaps adaption

### ISSUE THREAD

**Issue by u-fischer** [aminophen/platex-tools#14]
We released a latex-dev version some days ago. 
In this dev release we implemented a new hook system and extended the existing set of hooks.

Details can be found in the announcement:
https://www.latex-project.org/news/2020/07/22/latex-dev-2020-10-1b/

Beside other the new hook system emulate everyshi (and  suppress the loading of everyshi). There is an pxeveryshi in platex-tools which perhaps need to be adapted to this change. I didn't find a real breaking example as I don't know where this style is used, but it could e.g. be that the code the style is trying to add gets lost, or that because of the use of \box\@cclv it errors with the new latex.  Please check if you can find something. Check also if the new hook system offers sufficient support for your use cases.

Ulrike

**Comment by aminophen** [comment]
@u-fischer Thanks for the headsup.

* The tests/ directory contains examples where px... packages are necessary to avoid errors on pLaTeX.
* Besides pxeveryshi, I notice that pxatbegshi also needs adapted since it is not compatible with  \shipout within new ltshipout.dtx.

I will examine these.

**Comment by u-fischer** [comment]
@aminophen  Thanks. We hope that the new hooks cover all sensible use cases and make the various packages superfluous.  
Frank wrote here some suggestions regarding transfering packages: https://listserv.uni-heidelberg.de/cgi-bin/wa?A2=LATEX-L;22740d74.2007&S=

**Comment by aminophen** [comment]
@u-fischer Looking briefly, I think I still need to redefine macros instead of simply using newly provided hooks.

> We hope that the new hooks cover all sensible use cases and make the various packages superfluous.

Please note that my current packages (pxeveryshi, pxatbegshi) do not attempt to define 'WHAT I want to execute within the hook' but instead 'HOW I want to execute the hook'.  Specifically, I want to execute codes always inside \yoko (= Japanese horizontal writing) direction even when the document is written in \tate (= vertical) direction.  (The fact that "all contents of a box being shipped out must be placed inside \yoko direction" comes from the ancient design of pTeX engine and pLaTeX format, so any macros running on pLaTeX must conform to that rule.  I don't want to trouble you LaTeX team to support such an engine-specific design issue.)

**Comment by u-fischer** [comment]
@aminophen doesn't that mean simply that you always want \yoko as the first command in the hook? Can't you  add the command to the hook in the format and then it is there? I mean the hooks are not longer provided by packages loaded later, the package commands are only wrappers around the kernel hooks.
If this doesn't work please open an issue at the latex github so that we can discuss it there. These hooks should be useable for everyone  including the platex user ;-)

**Comment by aminophen** [comment]
@u-fischer I don't think that would work for all cases, as I've tested that years ago.  The command \yoko should be executed at the very beginning of the "list" (= node list), but the first command in the hook is too late (the "list" is already started).

**Comment by u-fischer** [comment]
Then please open an issue, perhaps along with an example, so that we can discuss it. I'm quite confident that we could add a special platex-hook there.

**Comment by aminophen** [comment]
As I wrote in https://github.com/aminophen/gentombow/issues/11#issuecomment-698888302, pLaTeX 2020-10-01 will be adjusted to work with the new ltshipout code; anticipating that, I decided to abandon pxeveryshi and pxatbegshi (silently \endinput as no-op) on the new LaTeX. The new version of two packages are released as 2020-09-27.
